#!/usr/bin/env python3
"""generate_gd.py — emit GDScript FlatBuffers accessors from a .bfbs schema.

Usage:
    flatc --schema -b -o . schema.fbs          # produces schema.bfbs
    python generate_gd.py schema.bfbs out_generated.gd

Requires: pip install flatbuffers, and reflection.fbs compiled with
    flatc --python reflection.fbs   (point --reflect-path at its output)

Emits a single .gd file containing one inner class per table plus enum
constants. Read side wraps the pure-GDScript FlatBuffer runtime; build side
emits create_*() functions taking FlatBufferBuilder.
"""
import argparse
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "tests", "gen_py"))
sys.path.insert(0, os.environ.get("REFLECT_GEN", ""))
from reflection.Schema import Schema  # noqa: E402
from reflection.BaseType import BaseType  # noqa: E402

# BaseType -> (reader getter, builder add, size)
SCALAR = {
    BaseType.Bool: ("get_bool", "add_bool_field", 1),
    BaseType.Byte: ("get_i8", "add_i8_field", 1),
    BaseType.UByte: ("get_u8", "add_u8_field", 1),
    BaseType.UType: ("get_u8", "add_u8_field", 1),
    BaseType.Short: ("get_i16", "add_i16_field", 2),
    BaseType.UShort: ("get_u16", "add_u16_field", 2),
    BaseType.Int: ("get_i32", "add_i32_field", 4),
    BaseType.UInt: ("get_u32", "add_u32_field", 4),
    BaseType.Long: ("get_i64", "add_i64_field", 8),
    BaseType.ULong: ("get_u64", "add_u64_field", 8),
    BaseType.Float: ("get_f32", "add_f32_field", 4),
    BaseType.Double: ("get_f64", "add_f64_field", 8),
}
VEC_GET = {
    BaseType.Bool: "get_vector_bool", BaseType.Byte: "get_vector_i8",
    BaseType.UByte: "get_vector_u8", BaseType.UType: "get_vector_u8",
    BaseType.Short: "get_vector_i16", BaseType.UShort: "get_vector_u16",
    BaseType.Int: "get_vector_i32", BaseType.UInt: "get_vector_u32",
    BaseType.Long: "get_vector_i64", BaseType.ULong: "get_vector_u64",
    BaseType.Float: "get_vector_f32", BaseType.Double: "get_vector_f64",
    BaseType.String: "get_vector_string",
}
VEC_ELEM_SIZE = {1: 1, 2: 2, 3: 1, 4: 1, 5: 1, 6: 2, 7: 2, 8: 4, 9: 4, 10: 8, 11: 8, 12: 4, 13: 8}

def snake(name: bytes) -> str:
    return name.decode()

def gd_ident(name: str) -> str:
    out, up = [], True
    for ch in name:
        if ch.isupper() and not up:
            out.append("_")
        up = ch.isupper()
        out.append(ch.lower())
    return "".join(out)

# Godot built-in/global names a generated class must not shadow
RESERVED = {"Error", "Object", "RefCounted", "String", "StringName", "Array",
            "Dictionary", "Callable", "Signal", "Vector2", "Vector3", "Vector4",
            "Color", "Transform2D", "Transform3D", "Quaternion", "Basis",
            "AABB", "Rect2", "Plane", "Node", "Resource", "PackedByteArray"}

def safe(name: str) -> str:
    return name + "FB" if name in RESERVED else name

def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("bfbs")
    ap.add_argument("out")
    ap.add_argument("--class-name", default="FBSchema")
    args = ap.parse_args()

    schema = Schema.GetRootAs(open(args.bfbs, "rb").read(), 0)
    objects = [schema.Objects(i) for i in range(schema.ObjectsLength())]
    enums = [schema.Enums(i) for i in range(schema.EnumsLength())]
    obj_by_index = {i: o for i, o in enumerate(objects)}

    lines = [f"# GENERATED by generate_gd.py from {os.path.basename(args.bfbs)} — do not edit",
             "class_name %s" % args.class_name, "",
             "const FlatBuffer_ = preload(\"res://addons/godot_flatbuffers/flatbuffer.gd\")",
             "const FlatBufferBuilder_ = preload(\"res://addons/godot_flatbuffers/flatbuffer_builder.gd\")",
             ""]

    # enums -> consts
    for e in enums:
        ename = e.Name().decode().replace(".", "_")
        lines.append(f"class {ename}:")
        for i in range(e.ValuesLength()):
            v = e.Values(i)
            lines.append(f"\tconst {snake(v.Name()).upper()} = {v.Value()}")
        lines.append("")

    for o in objects:
        if o.IsStruct():
            continue
        cname = safe(o.Name().decode().split(".")[-1])
        lines.append(f"class {cname}:")
        lines.append("\tvar _t: FlatBuffer_")
        lines.append("\tstatic func get_root_as(buf: PackedByteArray) -> %s:" % cname)
        lines.append("\t\treturn wrap_fb(FlatBuffer_.root(buf))")
        lines.append("\tstatic func wrap_fb(fb: FlatBuffer_) -> %s:" % cname)
        lines.append("\t\tif fb == null: return null")
        lines.append("\t\tvar x := %s.new()" % cname)
        lines.append("\t\tx._t = fb")
        lines.append("\t\treturn x")

        fields = [o.Fields(i) for i in range(o.FieldsLength())]
        for f in fields:
            fn = snake(f.Name())
            slot = f.Id()
            bt = f.Type().BaseType()
            et = f.Type().Element()
            dflt_i, dflt_r = f.DefaultInteger(), f.DefaultReal()
            if bt == BaseType.String:
                lines.append(f"\tfunc {fn}() -> String: return _t.get_string({slot})")
            elif bt == BaseType.Obj:
                tn = safe(obj_by_index[f.Type().Index()].Name().decode().split(".")[-1])
                lines.append(f"\tfunc {fn}() -> {tn}: return {tn}.wrap_fb(_t.get_table({slot}))")
            elif bt == BaseType.Union:
                # `{name}_type` accessor comes from the separately-emitted UType field
                lines.append(f"\tfunc {fn}() -> FlatBuffer_: return _t.get_table({slot})")
            elif bt == BaseType.Vector:
                if et == BaseType.Obj:
                    tn = safe(obj_by_index[f.Type().Index()].Name().decode().split(".")[-1])
                    lines.append(f"\tfunc {fn}_len() -> int: return _t.vector_len({slot})")
                    lines.append(f"\tfunc {fn}(i: int) -> {tn}: return {tn}.wrap_fb(_t.get_vector_table({slot}, i))")
                elif et == BaseType.String:
                    lines.append(f"\tfunc {fn}_len() -> int: return _t.vector_len({slot})")
                    lines.append(f"\tfunc {fn}(i: int) -> String: return _t.get_vector_string({slot}, i)")
                else:
                    g = VEC_GET.get(et, "get_vector_i32")
                    lines.append(f"\tfunc {fn}_len() -> int: return _t.vector_len({slot})")
                    lines.append(f"\tfunc {fn}(i: int) -> Variant: return _t.{g}({slot}, i)")
            else:
                g, _, _ = SCALAR.get(bt, ("get_i32", "add_i32_field", 4))
                is_float = bt in (BaseType.Float, BaseType.Double)
                d = dflt_r if is_float else dflt_i
                drepr = repr(d) if is_float else str(d)
                lines.append(f"\tfunc {fn}() -> Variant: return _t.{g}({slot}, {drepr})")

        # create_* builder
        params = []
        body = [f"\t\tb.start_table({o.FieldsLength()})"]
        for f in fields:
            fn = snake(f.Name())
            bt = f.Type().BaseType()
            if bt == BaseType.Union:
                # flatc already emits a `{name}_type` UType field — the union
                # itself contributes only the data offset param/write.
                params.append(f"{fn}_off: int = 0")
                body.append(f"\t\tb.add_offset_field({f.Id()}, {fn}_off, 0)")
                continue
            if bt in (BaseType.String, BaseType.Obj, BaseType.Vector):
                params.append(f"{fn}_off: int = 0")
                body.append(f"\t\tb.add_offset_field({f.Id()}, {fn}_off, 0)")
            else:
                _, adder, _ = SCALAR.get(bt, ("", "add_i32_field", 4))
                is_float = bt in (BaseType.Float, BaseType.Double)
                d = f.DefaultReal() if is_float else f.DefaultInteger()
                params.append(f"{fn}: {'float' if is_float else 'int'} = {d}")
                body.append(f"\t\tb.{adder}({f.Id()}, {fn}, {d})")
        lines.append("")
        lines.append(f"\tstatic func create_{gd_ident(cname)}(b: FlatBufferBuilder_, {', '.join(params)}) -> int:")
        lines.extend(body)
        lines.append("\t\treturn b.end_table()")
        lines.append("")
    open(args.out, "w", encoding="utf-8").write("\n".join(lines))
    print(f"wrote {args.out}: {len(objects)} tables, {len(enums)} enums")
    return 0

if __name__ == "__main__":
    sys.exit(main())
